### ISSUE TITLE
已经完全支持V5了吗？

### ISSUE THREAD

**Issue by panxianhai** [zhouaini528/okex-php#3]

**Comment by zhouaini528** [comment]
V5官方API暂时未开放，听说是4月初开放， 我只是先完成了接口，就等开放测试了。

**Comment by panxianhai** [comment]
模拟的可以进行测试了

**Comment by zhouaini528** [comment]
V5 API 已经在模拟上测试通过，就等官方开放了，   希望对你有用。
[https://github.com/zhouaini528/okex-php/tree/master/tests/okex_v5](https://github.com/zhouaini528/okex-php/tree/master/tests/okex_v5)
