### ISSUE TITLE
method_exists(): Argument #1 ($object_or_class) must be of type object|string, null given

### ISSUE THREAD

**Issue by pavelforever** [zhouaini528/okex-php#5]
Hello, time to time I get this error "method_exists(): Argument #1 ($object_or_class) must be of type object|string, null given". Is seems in RequestException somehow fills with null. Here is screenshot
![mintty_zrZI0rywYI](https://user-images.githubusercontent.com/9401132/136579847-9c4492fb-ad68-42c9-8eb9-4cf097f5bb03.png)
.

**Comment by zhouaini528** [comment]
Thank you for your discovery. Did you use PHP version 8?

**Comment by pavelforever** [comment]
> Thank you for your discovery. Did you use PHP version 8?

Yes, it's PHP 8.0.10

**Comment by zhouaini528** [comment]
I will fix this problem soon. The reason for it is [https://github.com/wintercms/winter/issues/207](https://github.com/wintercms/winter/issues/207)

**Comment by zhouaini528** [comment]
I have fixed. Please composer update to 2.1.8
If you have any other questions, please feel free to contact me

**Comment by pavelforever** [comment]
> I have fixed. Please composer update to 2.1.8 If you have any other questions, please feel free to contact me

Thank you! As I see now it will throw an Exception if any issue occured in request. Is there a way how I can make several request attempts if issue happened? Now on any problem with request my script dies. Yes, I can wrap up each method in try catch and cycle it through attempts, but maybe there is a universal way to do it?

**Comment by zhouaini528** [comment]
Your application needs a queue mechanism. If there is a script error, you can re-initiate the request at a few seconds to check whether the order is complete.
